# # 없어진 기록 찾기
# SELECT OUTS.ANIMAL_ID, OUTS.NAME
# FROM ANIMAL_OUTS OUTS
# LEFT OUTER JOIN ANIMAL_INS INS
# ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
# WHERE INS.ANIMAL_ID IS NULL
# ORDER BY OUTS.ANIMAL_ID
#
# # 있었는데요 없었습니다
# SELECT INS.ANIMAL_ID, INS.NAME
# FROM ANIMAL_INS INS
# LEFT OUTER JOIN ANIMAL_OUTS OUTS
# ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
# WHERE INS.DATETIME > OUTS.DATETIME
# ORDER BY INS.DATETIME
#
# # 오랜 기간 보호한 동물(1)
# SELECT *
# FROM
#     (SELECT INS.NAME, INS.DATETIME
#      FROM ANIMAL_INS INS
#      LEFT JOIN ANIMAL_OUTS OUTS
#      ON  INS.ANIMAL_ID = OUTS.ANIMAL_ID
#      WHERE OUTS.ANIMAL_ID IS NULL
#      ORDER BY INS.DATETIME
#     )
# WHERE ROWNUM <=3
#
# # 보호소에서 중성화한 동물
# SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
# FROM ANIMAL_INS INS
# INNER JOIN ANIMAL_OUTS OUTS
# ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
# WHERE INS.SEX_UPON_INTAKE LIKE 'Intact%'
# AND (OUTS.SEX_UPON_OUTCOME LIKE 'Spayed%'
#  OR OUTS.SEX_UPON_OUTCOME LIKE 'Neutered%')
# ORDER BY OUTS.ANIMAL_ID
#
# # 오랜 기간 보호한 동물(2)
# SELECT ANIMAL_ID, NAME
# FROM
#     (SELECT OUTS.ANIMAL_ID, OUTS.NAME, OUTS.DATETIME - INS.DATETIME 보호기간
#      FROM ANIMAL_INS INS
#      INNER JOIN ANIMAL_OUTS OUTS
#      ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
#      WHERE OUTS.ANIMAL_ID IS NOT NULL
#      ORDER BY 보호기간 DESC
# )
# WHERE ROWNUM <=2
#
# # 우유와 요거트가 담긴 장바구니
# SELECT M.CART_ID
# FROM
# (SELECT CART_ID
#  FROM CART_PRODUCTS
#  WHERE NAME = 'Milk') M,
# (SELECT CART_ID
# FROM CART_PRODUCTS
# WHERE NAME = 'Yogurt') Y
# WHERE M.CART_ID = Y.CART_ID
# ORDER BY CART_ID


# # 다른 풀이
# SELECT CART_ID
#   FROM CART_PRODUCTS
#  WHERE NAME = '우유'
# INTERSECT
# SELECT CART_ID
#   FROM CART_PRODUCTS
#  WHERE NAME = '요거트'
#  ORDER BY CART_ID

# # 입양 시각 구하기(2)
# SELECT L.HOUR, NVL(COUNT, 0) COUNT
# FROM
#     (SELECT TO_CHAR(DATETIME, 'HH24') HOUR, COUNT(*) COUNT
#      FROM ANIMAL_OUTS
#      GROUP BY TO_CHAR(DATETIME, 'HH24')
#      ORDER BY HOUR) TIME,
#      (SELECT LEVEL -1 HOUR
#      FROM DUAL CONNECT BY LEVEL<=24) L
# WHERE L.HOUR = TIME.HOUR(+)
# ORDER BY L.HOUR
